name: calculator
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  share: ^0.6.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.2.0

flutter_native_splash:
  color: "#000000"
  image: assets/icon.png
  android: true
  ios: true

flutter_icons:
  image_path: "assets/icon.png"
  android: true 
  ios: true


flutter:
  fonts:
    - family: calculator
      fonts:
        - asset: fonts/Calculator.ttf  
  uses-material-design: true

assets: 
  - assets/icon.png

  - uses-material-design: true

  